### ISSUE TITLE
kernel_timer.cc build failed with "error: 'uint64' was not declared in this scope  domain_cycles.end(), uint64{0})"

### ISSUE THREAD

**Issue by williamyang1** [google/nvidia_libs_test#10]
Build cudnn_benchmark
bazel run  //:cudnn_benchmark -c opt --action_env=CUDNN_PATH=/data/tmp/cuda --action_env=CUDA_PATH=/data/tmp/cuda
kernel_timer.cc build failed with the following error:
###############
kernel_timer.cc:194:68: error: 'uint64' was not declared in this scope
                                               domain_cycles.end(), uint64{0});
                                                                    ^
################
This error was by caused by latest commit a378e0f
It should be uint64_t{0}

**Comment by chsigg** [comment]
Thanks for reporting.
